// www.cineby.sc — Luna/Sora module
// Auto-generated by Luna Module Generator

const TMDB_API_KEY = "a0a41f5c8f26ed6332b7d8b5f0ae9278";

async function searchResults(query) {
  try {
    const encodedQuery = encodeURIComponent(query);
    const response = await fetch(
      `https://api.themoviedb.org/3/search/multi?api_key=${TMDB_API_KEY}&query=${encodedQuery}&include_adult=false`
    );
    const data = await response.json();
    
    if (!data.results || !Array.isArray(data.results)) {
      return [];
    }
    
    const results = data.results
      .filter(item => (item.media_type === 'movie' || item.media_type === 'tv') && item.poster_path)
      .map(item => {
        const title = item.title || item.name || 'Unknown';
        const mediaType = item.media_type;
        return {
          title: title,
          image: item.poster_path ? `https://image.tmdb.org/t/p/w342${item.poster_path}` : '',
          href: JSON.stringify({ id: item.id, type: mediaType, title: title })
        };
      });
    
    return results;
  } catch (error) {
    console.error('Search error:', error);
    return [];
  }
}

async function extractDetails(href) {
  try {
    const parsed = JSON.parse(href);
    const tmdbId = parsed.id;
    const mediaType = parsed.type;
    const title = parsed.title;
    
    if (mediaType === 'movie') {
      const response = await fetch(
        `https://api.themoviedb.org/3/movie/${tmdbId}?api_key=${TMDB_API_KEY}`
      );
      const data = await response.json();
      
      return {
        title: data.title || title,
        image: data.poster_path ? `https://image.tmdb.org/t/p/w500${data.poster_path}` : '',
        episodes: [
          {
            href: JSON.stringify({ id: tmdbId, type: 'movie' }),
            title: data.title || 'Movie',
            season: 1,
            episode: 1
          }
        ]
      };
    } else if (mediaType === 'tv') {
      const detailsResponse = await fetch(
        `https://api.themoviedb.org/3/tv/${tmdbId}?api_key=${TMDB_API_KEY}`
      );
      const detailsData = await detailsResponse.json();
      
      const episodes = [];
      const seasons = detailsData.seasons || [];
      
      for (const season of seasons) {
        const seasonNumber = season.season_number;
        if (seasonNumber === 0) continue;
        
        const seasonResponse = await fetch(
          `https://api.themoviedb.org/3/tv/${tmdbId}/season/${seasonNumber}?api_key=${TMDB_API_KEY}`
        );
        const seasonData = await seasonResponse.json();
        
        if (seasonData.episodes && Array.isArray(seasonData.episodes)) {
          for (const ep of seasonData.episodes) {
            const epNumber = ep.episode_number;
            const epTitle = ep.name || `Episode ${epNumber}`;
            
            episodes.push({
              href: JSON.stringify({ 
                id: tmdbId, 
                type: 'tv', 
                season: seasonNumber, 
                episode: epNumber 
              }),
              title: `S${seasonNumber}E${epNumber}: ${epTitle}`,
              season: seasonNumber,
              episode: epNumber
            });
          }
        }
      }
      
      return {
        title: detailsData.name || title,
        image: detailsData.poster_path ? `https://image.tmdb.org/t/p/w500${detailsData.poster_path}` : '',
        episodes: episodes
      };
    }
    
    return { title: title, episodes: [] };
  } catch (error) {
    console.error('Details error:', error);
    return { title: 'Unknown', episodes: [] };
  }
}

async function extractStreamUrl(href) {
  try {
    const parsed = JSON.parse(href);
    const tmdbId = parsed.id;
    const mediaType = parsed.type;

    if (mediaType === 'movie') {
      return `https://www.cineby.sc/embed/movie?tmdb=${tmdbId}`;
    } else {
      const season  = parsed.season;
      const episode = parsed.episode;
      return `https://www.cineby.sc/embed/tv?tmdb=${tmdbId}&season=${season}&episode=${episode}`;
    }
  } catch (error) {
    console.error('Stream URL error:', error);
    return '';
  }
}
