// flixhq.to — Luna/Sora module
// Auto-generated by Luna Module Generator

async function searchResults(query) {
  try {
    const searchUrl = `${baseUrl}/search/${encodeURIComponent(query)}`;
    const response = await fetch(searchUrl);
    const html = await response.text();
    
    const results = [];
    
    // Parse film items from search results
    const filmItemRegex = /<div class="flw-item"[^>]*>[\s\S]*?<a[^>]*href="([^"]+)"[^>]*title="([^"]+)"[\s\S]*?<img[^>]*data-src="([^"]+)"[^>]*>/g;
    
    let match;
    while ((match = filmItemRegex.exec(html)) !== null) {
      const href = match[1];
      const title = match[2];
      const image = match[3];
      
      results.push({
        title: title,
        image: image,
        href: href
      });
    }
    
    // Alternative parsing pattern
    if (results.length === 0) {
      const altRegex = /<a[^>]*href="(\/(?:movie|tv)\/[^"]+)"[^>]*title="([^"]+)"[\s\S]*?<img[^>]*(?:data-src|src)="([^"]+)"/g;
      while ((match = altRegex.exec(html)) !== null) {
        results.push({
          title: match[2],
          image: match[3],
          href: match[1]
        });
      }
    }
    
    return results;
  } catch (error) {
    console.log('Search error:', error);
    return [];
  }
}

async function extractDetails(href) {
  try {
    const fullUrl = href.startsWith('http') ? href : `${baseUrl}${href}`;
    const response = await fetch(fullUrl);
    const html = await response.text();
    
    // Extract title
    const titleMatch = html.match(/<h2 class="heading-name"[^>]*>[\s\S]*?<a[^>]*>([^<]+)<\/a>/);
    const title = titleMatch ? titleMatch[1].trim() : 'Unknown Title';
    
    // Extract image
    const imageMatch = html.match(/<img[^>]*class="film-poster-img"[^>]*(?:data-src|src)="([^"]+)"/);
    const image = imageMatch ? imageMatch[1] : '';
    
    // Extract data-id for AJAX calls
    const dataIdMatch = html.match(/data-id="(\d+)"/);
    const dataId = dataIdMatch ? dataIdMatch[1] : null;
    
    // Determine if movie or TV
    const isMovie = href.includes('/movie/');
    
    const episodes = [];
    
    if (isMovie) {
      // For movies, get episodes via AJAX
      if (dataId) {
        const episodesUrl = `${baseUrl}/ajax/movie/episodes/${dataId}`;
        const episodesResponse = await fetch(episodesUrl);
        const episodesHtml = await episodesResponse.text();
        
        // Extract server links
        const serverMatch = episodesHtml.match(/data-linkid="(\d+)"/);
        const linkId = serverMatch ? serverMatch[1] : dataId;
        
        episodes.push({
          href: linkId,
          title: title,
          season: 1,
          episode: 1
        });
      } else {
        episodes.push({
          href: href,
          title: title,
          season: 1,
          episode: 1
        });
      }
    } else {
      // For TV shows, get seasons then episodes
      if (dataId) {
        const seasonsUrl = `${baseUrl}/ajax/tv/seasons/${dataId}`;
        const seasonsResponse = await fetch(seasonsUrl);
        const seasonsHtml = await seasonsResponse.text();
        
        // Extract season IDs
        const seasonRegex = /data-id="(\d+)"[^>]*>[\s\S]*?Season\s*(\d+)/gi;
        const seasons = [];
        let seasonMatch;
        
        while ((seasonMatch = seasonRegex.exec(seasonsHtml)) !== null) {
          seasons.push({
            id: seasonMatch[1],
            number: parseInt(seasonMatch[2], 10)
          });
        }
        
        // Get episodes for each season
        for (const season of seasons) {
          const episodesUrl = `${baseUrl}/ajax/tv/season/episodes/${season.id}`;
          const episodesResponse = await fetch(episodesUrl);
          const episodesHtml = await episodesResponse.text();
          
          // Extract episode data
          const episodeRegex = /data-id="(\d+)"[^>]*title="([^"]*)"[\s\S]*?Eps\s*(\d+)/gi;
          let episodeMatch;
          
          while ((episodeMatch = episodeRegex.exec(episodesHtml)) !== null) {
            const epId = episodeMatch[1];
            const epTitle = episodeMatch[2] || `Episode ${episodeMatch[3]}`;
            const epNum = parseInt(episodeMatch[3], 10);
            
            episodes.push({
              href: epId,
              title: epTitle,
              season: season.number,
              episode: epNum
            });
          }
          
          // Alternative episode parsing
          if (episodes.filter(e => e.season === season.number).length === 0) {
            const altEpRegex = /data-id="(\d+)"[^>]*>[\s\S]*?<span>Eps\s*(\d+)[^<]*<\/span>[\s\S]*?<h3[^>]*>([^<]+)<\/h3>/gi;
            while ((episodeMatch = altEpRegex.exec(episodesHtml)) !== null) {
              episodes.push({
                href: episodeMatch[1],
                title: episodeMatch[3].trim(),
                season: season.number,
                episode: parseInt(episodeMatch[2], 10)
              });
            }
          }
        }
      }
    }
    
    return {
      title: title,
      image: image,
      episodes: episodes
    };
  } catch (error) {
    console.log('Details error:', error);
    return {
      title: 'Unknown',
      image: '',
      episodes: []
    };
  }
}

async function extractStreamUrl(href) {
  try {
    // href is the episode/movie data-id
    const serversUrl = `${baseUrl}/ajax/episode/servers/${href}`;
    const serversResponse = await fetch(serversUrl);
    const serversHtml = await serversResponse.text();
    
    // Extract server IDs - prefer Vidcloud or UpCloud
    const serverRegex = /data-id="(\d+)"[^>]*title="([^"]+)"/gi;
    let serverMatch;
    let selectedServerId = null;
    let fallbackServerId = null;
    
    while ((serverMatch = serverRegex.exec(serversHtml)) !== null) {
      const serverId = serverMatch[1];
      const serverName = serverMatch[2].toLowerCase();
      
      if (serverName.includes('vidcloud') || serverName.includes('upcloud')) {
        selectedServerId = serverId;
        break;
      }
      if (!fallbackServerId) {
        fallbackServerId = serverId;
      }
    }
    
    const finalServerId = selectedServerId || fallbackServerId || href;
    
    // Get embed URL from server
    const sourcesUrl = `${baseUrl}/ajax/episode/sources/${finalServerId}`;
    const sourcesResponse = await fetch(sourcesUrl);
    const sourcesData = await sourcesResponse.json();
    
    if (sourcesData && sourcesData.link) {
      // Extract embed URL
      const embedUrl = sourcesData.link;
      
      // Try to get direct stream from embed
      if (embedUrl.includes('rabbitstream') || embedUrl.includes('vidcloud') || embedUrl.includes('upcloud')) {
        // For rabbitstream-type embeds, we need to extract the actual stream
        const embedId = embedUrl.split('/').pop().split('?')[0];
        
        // Try to get sources from embed API
        try {
          const embedSourceUrl = embedUrl.replace('/embed/', '/ajax/embed/').replace('/e/', '/ajax/e/') + '/getSources';
          const embedResponse = await fetch(embedSourceUrl, {
            headers: {
              'X-Requested-With': 'XMLHttpRequest',
              'Referer': embedUrl
            }
          });
          const embedData = await embedResponse.json();
          
          if (embedData && embedData.sources) {
            if (Array.isArray(embedData.sources) && embedData.sources.length > 0) {
              return embedData.sources[0].file || embedData.sources[0].url;
            }
            if (typeof embedData.sources === 'string') {
              return embedData.sources;
            }
          }
        } catch (e) {
          console.log('Embed extraction failed, returning embed URL');
        }
      }
      
      // Return embed URL as fallback
      return embedUrl;
    }
    
    // Direct fallback - try movie sources endpoint
    const movieSourcesUrl = `${baseUrl}/ajax/movie/sources/${href}`;
    const movieResponse = await fetch(movieSourcesUrl);
    const movieData = await movieResponse.json();
    
    if (movieData && movieData.link) {
      return movieData.link;
    }
    
    return '';
  } catch (error) {
    console.log('Stream error:', error);
    return '';
  }
}